# This is a basic workflow to help you get started with Actions

name: Check Package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  schedule:
    - cron: '10 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - run: dotnet restore
    - uses: MeilCli/nuget-update-check-action@v2
      id: outdated
