# This is a basic workflow to help you get started with Actions

name: Check Package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  schedule:
    - cron: '5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'
    - run: dotnet restore
    - name: nuget update checker
      uses: MeilCli/nuget-update-check-action@v2
